const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let auth=JSON.parse(localStorage.getItem('goaiAuth')||'null'), match=null, plan=[];
const actionNames={short_loan_borrow:'短期贷款',long_loan_borrow:'长期贷款',receivable_discount:'应收贴现',develop_product:'开发产品',develop_market:'开发市场',develop_iso:'开发认证',rent_workshop:'租赁厂房',buy_workshop:'购买厂房',sell_workshop:'出售厂房',buy_product_line:'建设产线',convert_product_line:'生产线转产',sell_product_line:'出售产线',material_order:'订购原料',emergency_purchase:'紧急购料',emergency_product_purchase:'紧急购成品',production:'安排生产',order_delivery:'交付订单',advertising:'投放广告',select_order:'选择订单',auction_bid:'参与竞单',spy_information_purchase:'购买企业信息',hold:'保持'};
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(auth?.token)headers.Authorization=`Bearer ${auth.token}`;const r=await fetch(path,{...options,headers});const body=await r.json();if(!r.ok)throw new Error(body.error||'请求失败');return body}
function saveAuth(v){auth=v;localStorage.setItem('goaiAuth',JSON.stringify(v))}
function showLobby(){ $('#lobby-view').classList.remove('hidden');$('#game-view').classList.add('hidden') }
function showGame(){ $('#lobby-view').classList.add('hidden');$('#game-view').classList.remove('hidden') }
function message(text,type='info'){const n=$('#game-message');n.textContent=text;n.classList.toggle('hidden',!text);n.style.background=type==='error'?'#f9e2df':'#fff5d6'}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#create-form').classList.toggle('hidden',b.dataset.tab!=='create');$('#join-form').classList.toggle('hidden',b.dataset.tab!=='join')});
$$('.game-tab').forEach(b=>b.onclick=()=>{$$('.game-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.game-screen').forEach(x=>x.classList.add('hidden'));$(`#screen-${b.dataset.screen}`).classList.remove('hidden')});
$('#create-form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));data.team_count=+data.team_count;data.human_slots=+data.human_slots;data.seed=+data.seed;const out=await api('/api/matches',{method:'POST',body:JSON.stringify(data)});saveAuth({matchId:out.match_id,...out.credentials});match=out;showGame();render()}catch(err){$('#lobby-error').textContent=err.message}};
$('#join-form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));const out=await api(`/api/matches/${data.match_id}/join`,{method:'POST',body:JSON.stringify(data)});saveAuth({matchId:data.match_id,...out.credentials});match=out.match;showGame();render()}catch(err){$('#lobby-error').textContent=err.message}};
async function refresh(){if(!auth?.matchId)return;try{match=await api(`/api/matches/${auth.matchId}`);showGame();render()}catch(err){message(err.message,'error')}}
$('#start-match').onclick=async()=>{try{match=await api(`/api/matches/${match.match_id}/start`,{method:'POST',body:'{}'});render()}catch(err){message(err.message,'error')}};
$('#copy-code').onclick=()=>navigator.clipboard?.writeText(match.match_id).then(()=>message('加入码已复制'));
$('#export-match').onclick=async()=>{try{const payload=await api(`/api/matches/${match.match_id}/export`);const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${match.match_id}.json`;a.click();URL.revokeObjectURL(url)}catch(err){message(err.message,'error')}};
function addAction(action){plan.push(action);renderPlan()}
function params(action){return action.parameters||{}}
function renderPlan(){const root=$('#plan-list');if(!plan.length){root.innerHTML='<p class="muted">尚未添加动作；空方案会提交“保持”。</p>';return}root.innerHTML=plan.map((a,i)=>`<div class="plan-item"><strong>${i+1}. ${actionNames[a.action_type]||a.action_type}</strong><span>${escapeHtml(JSON.stringify(params(a)))}</span><button data-remove="${i}">×</button></div>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{plan.splice(+b.dataset.remove,1);renderPlan()})}
$('#clear-plan').onclick=()=>{plan=[];renderPlan()};
$$('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add;if(type==='loan'){const action_type=$('#loan-type').value,principal_wan=+$('#loan-amount').value;addAction({action_type,parameters:{principal_wan,...(action_type==='long_loan_borrow'?{term_years:4}:{term_quarters:4})}})}if(type==='factory')addAction({action_type:$('#factory-mode').value,parameters:{factory:$('#factory-name').value}});if(type==='line')addAction({action_type:'buy_product_line',parameters:{line_type:$('#line-type').value,product_id:$('#line-product').value}});if(type==='material')addAction({action_type:'material_order',parameters:{materials:{[$('#material-name').value]:+$('#material-quantity').value}}});if(type==='advertising')addAction({action_type:'advertising',parameters:{market:$('#ad-market').value,product_id:$('#ad-product').value,amount_wan:+$('#ad-amount').value}});if(type==='emergency-material')addAction({action_type:'emergency_purchase',parameters:{material_id:$('#emergency-material-name').value,quantity:+$('#emergency-material-quantity').value}});if(type==='emergency-product')addAction({action_type:'emergency_product_purchase',parameters:{product_id:$('#emergency-product-name').value,quantity:+$('#emergency-product-quantity').value}});if(type==='convert-line')addAction({action_type:'convert_product_line',parameters:{line_id:$('#asset-line').value,product_id:$('#convert-product').value}});if(type==='sell-line')addAction({action_type:'sell_product_line',parameters:{line_id:$('#asset-line').value}});if(type==='sell-factory')addAction({action_type:'sell_workshop',parameters:{factory_id:$('#asset-factory').value}});if(type==='spy')addAction({action_type:'spy_information_purchase',parameters:{target_team_id:$('#spy-team').value}})});
$('#submit-plan').onclick=async()=>{try{const action_bundle=plan.length?{actions:plan}:{action_type:'hold'},phase=match.decision_phase;const out=await api(`/api/matches/${match.match_id}/submit`,{method:'POST',body:JSON.stringify({action_bundle})});plan=[];match=out.match;render();message(out.submission.advanced?(phase==='operating'?'订单已经统一分配，请依据实际获单重新安排履约。':'本季度已结算，进入下一季度经营与申领。'):'决策已锁定，正在等待其他人类玩家。')}catch(err){message(err.message,'error')}};
$('#get-recommendation').onclick=async()=>{try{message('协同 Agent 正在联合预演资金、资格、产能、履约和订单……');const out=await api(`/api/matches/${match.match_id}/recommend`,{method:'POST',body:JSON.stringify({profile:'balanced'})});plan=out.recommendation.actions||[out.recommendation];renderPlan();message(`已载入 ${plan.length} 个经过风险重放的建议动作，可继续人工修改。`)}catch(err){message(err.message,'error')}};
$('#claim-selected').onclick=()=>{const state=match.observation?.private_state||{},ads=state.advertising||{};$$('#orders-table input:checked').forEach(box=>{const o=JSON.parse(box.dataset.order),common={order_id:o.order_id,market:o.market,product:o.product,submitted_at:Math.random()};if(o.order_type==='竞单')addAction({action_type:'auction_bid',parameters:{...common,bid_wan:o.total_price_wan}});else addAction({action_type:'select_order',parameters:{...common,product_advertising:+(ads[`${o.market}:${o.product}`]||0),market_advertising:Object.entries(ads).filter(([k])=>k.startsWith(`${o.market}:`)).reduce((s,[,v])=>s+(+v||0),0),total_advertising:Object.values(ads).reduce((s,v)=>s+(+v||0),0)}})});$$('[data-screen="command"]')[0].click();message('选中的订单申领已加入本季度联合方案。')};
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v,d=0){return Number(v||0).toFixed(d)}
function dataRows(title,rows){return `<div class="data-section"><h4>${title}</h4>${rows.length?rows.map(([a,b])=>`<div class="data-row"><span>${escapeHtml(a)}</span><span>${escapeHtml(typeof b==='object'?JSON.stringify(b):b)}</span></div>`).join(''):'<p class="muted">暂无数据</p>'}</div>`}
function populateSelect(id,items){const el=$(id),old=el.value;el.innerHTML=items.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');if(items.includes(old))el.value=old}
function render(){if(!match)return;const post=match.decision_phase==='post_allocation';$('#match-id').textContent=match.match_id;$('#match-name').textContent=match.name;$('#match-meta').textContent=`${match.team_count} 家企业 · ${match.human_slots} 个人类席位 · ${match.bot_policy} 对手 · 种子 ${match.seed}`;$('#period').textContent=match.period;$('#phase-pill').textContent=post?'获单后履约':'经营与申领';$('#status-pill').textContent={lobby:'等待加入',running:'比赛中',complete:'已结束'}[match.status]||match.status;$('#start-match').classList.toggle('hidden',match.status!=='lobby');$('#export-match').classList.toggle('hidden',match.status!=='complete');$('#start-match').disabled=match.open_human_slots>0;$('#player-team').textContent=match.player?.team_id||'观战';$('#submit-plan').disabled=match.status!=='running'||match.submitted_this_period;$('#submit-plan').textContent=post?'提交获单后履约方案':'提交经营与申领方案';$('#submit-hint').textContent=post?'全员提交后，裁判执行生产、交付、违约和财务结算并推进季度。':'全员提交后，裁判先按冲突规则分配订单，再开放获单后履约阶段。';
  if(match.status==='lobby'&&match.open_human_slots)message(`等待 ${match.open_human_slots} 位玩家加入。分享加入码：${match.match_id}`);else if(match.submitted_this_period)message('本季度决策已提交，等待其他玩家。');else if(match.status==='complete')message('比赛已经结束，可在赛场排名中查看终局结果。');else message('');
  const s=match.observation?.private_state||{};const own=match.team_status.find(x=>x.team_id===match.player?.team_id)||{};$('#metrics').innerHTML=[['现金',`${n(s.cash_wan)} 万`],['权益',`${n(s.owner_equity_wan)} 万`],['负债',`${n(s.debt_wan)} 万`],['评分代理',n(own.score,1)]].map(([a,b])=>`<div class="metric"><small>${a}</small><strong>${b}</strong></div>`).join('');$('#progress-text').textContent=`${Math.min(match.step,20)} / 20`;$('#progress-bar').style.width=`${Math.min(match.step/20*100,100)}%`;
  $('#capability-tags').innerHTML=[...(s.products||[]),...(s.markets||[]),...(s.iso||[])].map(x=>`<span>${escapeHtml(x)}</span>`).join('')||'<span>尚未开发</span>';const assigned=s.assigned_orders||[],delivered=s.delivered_orders||[],defaults=s.defaulted_orders||[];$('#order-summary').innerHTML=`在手订单：${assigned.filter(x=>!['已交','违约'].includes(x.status)).length}<br>累计交付：${delivered.length}<br>累计违约：${defaults.length}`;
  renderControls(s);renderOrders(match.observation?.public_state?.available_orders||[]);renderCompany(s);renderFeedback(s);renderRanking();renderPlan();
}
function renderControls(s){const c=match.rules_catalog||{};populateSelect('#factory-name',Object.keys(c.factories||{}));populateSelect('#line-type',Object.keys(c.production_lines||{}));populateSelect('#line-product',Object.keys(c.products||{}));populateSelect('#material-name',Object.keys(c.materials||{}));populateSelect('#ad-market',Object.keys(c.markets||{}));populateSelect('#ad-product',Object.keys(c.products||{}));populateSelect('#emergency-material-name',Object.keys(c.materials||{}));populateSelect('#emergency-product-name',Object.keys(c.products||{}));populateSelect('#convert-product',s.products||[]);populateSelect('#asset-line',(s.production_lines||[]).filter(x=>x.status==='ready').map(x=>x.line_id));populateSelect('#asset-factory',(s.factories||[]).filter(x=>x.ownership==='purchased').map(x=>x.factory_id));populateSelect('#spy-team',(match.team_status||[]).map(x=>x.team_id).filter(x=>x!==match.player?.team_id));const pending=new Set((s.pending_development||[]).map(x=>`${x.kind}:${x.target}`));const buttons=[];Object.keys(c.products||{}).filter(x=>!(s.products||[]).includes(x)&&!pending.has(`product:${x}`)).forEach(x=>buttons.push(`<button data-q="product" data-target="${x}">开发产品 ${x}</button>`));Object.keys(c.markets||{}).filter(x=>!(s.markets||[]).includes(x)&&!pending.has(`market:${x}`)).forEach(x=>buttons.push(`<button data-q="market" data-target="${x}">开发市场 ${x}</button>`));Object.keys(c.iso||{}).filter(x=>!(s.iso||[]).includes(x)&&!pending.has(`iso:${x}`)).forEach(x=>buttons.push(`<button data-q="iso" data-target="${x}">认证 ${x}</button>`));$('#qualification-actions').innerHTML=buttons.join('')||'<span class="muted">所有资格均已完成或在开发中</span>';$$('[data-q]').forEach(b=>b.onclick=()=>addAction({action_type:{product:'develop_product',market:'develop_market',iso:'develop_iso'}[b.dataset.q],parameters:{target:b.dataset.target}}));
  $('#receivable-actions').innerHTML=(s.receivables||[]).map(r=>`<button data-ar="${r.receivable_id}">贴现 ${r.receivable_id}（${n(r.amount_wan)}）</button>`).join('');$$('[data-ar]').forEach(b=>b.onclick=()=>addAction({action_type:'receivable_discount',parameters:{receivable_id:b.dataset.ar}}));
  $('#production-actions').innerHTML=(s.production_lines||[]).filter(l=>l.status==='ready').map((l,i)=>`<button data-prod="${i}">生产 ${l.product_id||'未指定'} · ${l.line_type}</button>`).join('')||'<span class="muted">暂无就绪产线</span>';$$('[data-prod]').forEach(b=>{const l=(s.production_lines||[]).filter(x=>x.status==='ready')[+b.dataset.prod];b.onclick=()=>addAction({action_type:'production',parameters:{product_id:l.product_id||s.products?.[0]||'P1',quantity:1,line_type:l.line_type}})});
  const outstanding=(s.assigned_orders||[]).filter(o=>!['已交','违约'].includes(o.status));$('#delivery-actions').innerHTML=outstanding.map(o=>`<button class="${(s.product_inventory?.[o.product]||0)>=o.quantity?'':'danger'}" data-deliver="${o.order_id}">交付 ${o.order_id} · ${o.product}×${o.quantity}</button>`).join('')||'<span class="muted">暂无待交订单</span>';$$('[data-deliver]').forEach(b=>b.onclick=()=>addAction({action_type:'order_delivery',parameters:{order_id:b.dataset.deliver}}))}
function renderOrders(orders){$('#orders-table').innerHTML=orders.slice(0,300).map(o=>`<tr><td><input type="checkbox" data-order='${escapeHtml(JSON.stringify(o))}'></td><td>${escapeHtml(o.order_id)}</td><td>${o.order_type}</td><td>${o.market}</td><td>${o.product}</td><td>${o.quantity}</td><td>${n(o.total_price_wan)}</td><td>${o.due_period}</td><td>${(o.required_iso||[]).join('+')||'-'}</td></tr>`).join('')||'<tr><td colspan="9" class="muted">本季度没有可见订单</td></tr>'}
function renderCompany(s){$('#assets-view').innerHTML=dataRows('资格',[['产品',(s.products||[]).join('、')],['市场',(s.markets||[]).join('、')],['ISO',(s.iso||[]).join('、')]])+dataRows('厂房',(s.factories||[]).map(x=>[x.factory_id,`${x.name} · ${x.ownership} · 容量 ${x.capacity}`]))+dataRows('生产线',[...(s.production_lines||[]),...(s.pending_lines||[])].map(x=>[x.line_id,`${x.line_type} · ${x.product_id} · ${x.status}`]))+dataRows('已购买情报',(s.intelligence_reports||[]).map(x=>[x.target_team_id,x.fields]));$('#finance-view').innerHTML=dataRows('产品库存',Object.entries(s.product_inventory||{}))+dataRows('原料库存',Object.entries(s.material_inventory||{}))+dataRows('长期贷款',(s.long_loans||[]).map(x=>[x.loan_id,`${n(x.principal_wan)} 万 · 到期 ${x.due_period_index}`]))+dataRows('短期贷款',(s.short_loans||[]).map(x=>[x.loan_id,`${n(x.principal_wan)} 万 · 到期 ${x.due_period_index}`]))+dataRows('应收款',(s.receivables||[]).map(x=>[x.receivable_id,`${n(x.amount_wan)} 万 · 到期 ${x.due_period_index}`]))}
function renderFeedback(s){const f=match.last_feedback;$('#feedback-view').innerHTML=f?`<p class="${f.action_status==='accepted'?'status-ok':'status-bad'}">${f.action_status} · 权益变化 ${n(f.reward,1)} · ${f.bankrupt?'已破产':'经营中'}</p>${(f.action_rejections||[]).map(x=>`<div class="feedback-event status-bad">${escapeHtml(x)}</div>`).join('')}${(f.events||[]).slice(-20).map(x=>`<div class="feedback-event"><strong>${escapeHtml(x.event_type)}</strong> · ${escapeHtml(x.period||f.period)}</div>`).join('')}`:'<p class="muted">尚无结算反馈</p>';$('#reports-view').innerHTML=(s.reports||[]).length?(s.reports||[]).map(r=>dataRows(`第 ${r.year} 年`,[['净利润',r.income_statement?.net_income_wan],['总资产',r.balance_sheet?.total_assets_wan],['权益',r.balance_sheet?.owner_equity_wan],['净现金流',r.cash_flow_statement?.net_cash_flow_wan]])).join(''):'<p class="muted">年度结束后自动生成资产负债表、利润表和现金流量表。</p>'}
function renderRanking(){const rows=[...(match.team_status||[])].sort((a,b)=>(b.score||0)-(a.score||0));$('#ranking-table').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}. ${r.team_id}</td><td class="${r.bankrupt?'status-bad':'status-ok'}">${r.bankrupt?'破产':'经营中'}</td><td>${n(r.development_potential,0)}</td><td>${n(r.score,1)}</td></tr>`).join('')}
if(auth?.matchId)refresh();else showLobby();setInterval(()=>{if(auth?.matchId&&match?.status!=='complete')refresh()},2500);
