const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let auth=JSON.parse(localStorage.getItem('goaiAuth')||'null'), match=null, plan=[];
const actionNames={short_loan_borrow:'短期贷款',long_loan_borrow:'长期贷款',receivable_discount:'应收贴现',develop_product:'开发产品',develop_market:'开发市场',develop_iso:'开发认证',rent_workshop:'租赁厂房',buy_workshop:'购买厂房',sell_workshop:'出售厂房',buy_product_line:'建设产线',convert_product_line:'生产线转产',sell_product_line:'出售产线',material_order:'订购原料',emergency_purchase:'紧急购料',emergency_product_purchase:'紧急购成品',production:'安排生产',order_delivery:'交付订单',advertising:'投放广告',select_order:'选择订单',auction_bid:'参与竞单',order_portfolio:'组合申领',spy_information_purchase:'购买企业信息',hold:'保持'};
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(auth?.token)headers.Authorization=`Bearer ${auth.token}`;const r=await fetch(path,{...options,headers});const body=await r.json();if(!r.ok)throw new Error(body.error||'请求失败');return body}
function saveAuth(v){auth=v;localStorage.setItem('goaiAuth',JSON.stringify(v))}
function clearAuth(){auth=null;match=null;plan=[];localStorage.removeItem('goaiAuth')}
function showLobby(){ $('#lobby-view').classList.remove('hidden');$('#game-view').classList.add('hidden') }
function showGame(){ $('#lobby-view').classList.add('hidden');$('#game-view').classList.remove('hidden') }
function message(text,type='info'){const n=$('#game-message');n.textContent=text;n.classList.toggle('hidden',!text);n.style.background=type==='error'?'#f9e2df':'#fff5d6'}
function allowed(type){return (match?.allowed_action_types||[]).includes(type)}
function toggleGuide(show){$('#guide-modal').classList.toggle('hidden',!show)}
$('#open-guide').onclick=()=>toggleGuide(true);$('#close-guide').onclick=()=>toggleGuide(false);$('#guide-start').onclick=()=>toggleGuide(false);$('#guide-modal').onclick=e=>{if(e.target===$('#guide-modal'))toggleGuide(false)};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#create-form').classList.toggle('hidden',b.dataset.tab!=='create');$('#join-form').classList.toggle('hidden',b.dataset.tab!=='join')});
$$('.game-tab').forEach(b=>b.onclick=()=>{$$('.game-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.game-screen').forEach(x=>x.classList.add('hidden'));$(`#screen-${b.dataset.screen}`).classList.remove('hidden')});
$('#create-form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));data.team_count=+data.team_count;data.human_slots=+data.human_slots;data.seed=+data.seed;const out=await api('/api/matches',{method:'POST',body:JSON.stringify(data)});saveAuth({matchId:out.match_id,...out.credentials});match=out;showGame();render()}catch(err){$('#lobby-error').textContent=err.message}};
$('#join-form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));const out=await api(`/api/matches/${data.match_id}/join`,{method:'POST',body:JSON.stringify(data)});saveAuth({matchId:data.match_id,...out.credentials});match=out.match;showGame();render()}catch(err){$('#lobby-error').textContent=err.message}};
async function refresh(){if(!auth?.matchId)return;try{match=await api(`/api/matches/${auth.matchId}`);showGame();render()}catch(err){message(err.message,'error')}}
$('#start-match').onclick=async()=>{try{match=await api(`/api/matches/${match.match_id}/start`,{method:'POST',body:'{}'});render()}catch(err){message(err.message,'error')}};
$('#back-lobby').onclick=()=>{clearAuth();showLobby();$('#lobby-error').textContent=''};
$('#advance-bots').onclick=async()=>{try{match=await api(`/api/matches/${match.match_id}/advance`,{method:'POST',body:'{}'});render()}catch(err){message(err.message,'error')}};
$('#run-bots').onclick=async()=>{try{$('#run-bots').disabled=true;message('全部 Agent 正在完成 5 年比赛……');match=await api(`/api/matches/${match.match_id}/run`,{method:'POST',body:'{}'});render();message('纯 Agent 比赛已完成，可查看排名并导出记录。')}catch(err){message(err.message,'error')}finally{$('#run-bots').disabled=false}};
$('#copy-code').onclick=()=>navigator.clipboard?.writeText(match.match_id).then(()=>message('加入码已复制'));
$('#export-match').onclick=async()=>{try{const payload=await api(`/api/matches/${match.match_id}/export`);const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${match.match_id}.json`;a.click();URL.revokeObjectURL(url)}catch(err){message(err.message,'error')}};
function addAction(action){if(!allowed(action.action_type)){message(`当前阶段不允许“${actionNames[action.action_type]||action.action_type}”。`,'error');return}plan.push(action);renderPlan()}
function params(action){return action.parameters||{}}
function actionSummary(action){
  const p=params(action),materialText=Object.entries(p.materials||{}).map(([key,value])=>`${key} × ${value}`).join('、');
  if(action.action_type==='short_loan_borrow')return`借入 ${n(p.principal_wan)} 万 · ${p.term_quarters||4} 季度`;
  if(action.action_type==='long_loan_borrow')return`借入 ${n(p.principal_wan)} 万 · ${p.term_years||4} 年`;
  if(action.action_type==='receivable_discount')return`贴现应收款 ${p.receivable_id||'已选择'}`;
  if(action.action_type==='develop_product')return`开发产品 ${p.target}`;
  if(action.action_type==='develop_market')return`开拓市场 ${p.target}`;
  if(action.action_type==='develop_iso')return`申请认证 ${p.target}`;
  if(['rent_workshop','buy_workshop'].includes(action.action_type))return p.factory||p.factory_id||'已选择厂房';
  if(action.action_type==='sell_workshop')return`处置厂房 ${p.factory_id||'已选择'}`;
  if(action.action_type==='buy_product_line')return`${p.line_type||'生产线'} · 面向 ${p.product_id||'已选择产品'}`;
  if(action.action_type==='convert_product_line')return`${p.line_id||'已选择产线'} 转产 ${p.product_id||'已选择产品'}`;
  if(action.action_type==='sell_product_line')return`处置产线 ${p.line_id||'已选择'}`;
  if(action.action_type==='material_order')return`订购 ${materialText||'已选择原料'}`;
  if(action.action_type==='emergency_purchase')return`${p.material_id||'原料'} × ${p.quantity||1}`;
  if(action.action_type==='emergency_product_purchase')return`${p.product_id||'产品'} × ${p.quantity||1}`;
  if(action.action_type==='production')return`${p.line_id||p.line_type||'产线'}生产 ${p.product_id||'产品'} × ${p.quantity||1}`;
  if(action.action_type==='order_delivery')return`交付订单 ${p.order_id||'已选择'}`;
  if(action.action_type==='advertising')return`${p.market||'市场'} · ${p.product_id||'产品'} · ${n(p.amount_wan)} 万`;
  if(action.action_type==='select_order')return`申领 ${p.order_id||'已选择订单'} · ${p.market||''} ${p.product||''}`.trim();
  if(action.action_type==='auction_bid')return`竞价 ${p.order_id||'已选择订单'} · 报价 ${n(p.bid_wan)} 万`;
  if(action.action_type==='order_portfolio'){const slots=p.candidate_slots||[],fallbacks=slots.reduce((sum,row)=>sum+Math.max(0,(row||[]).length-1),0);return`${p.target_count||slots.length} 个主订单槽位 · ${fallbacks} 个回退候选`}
  if(action.action_type==='spy_information_purchase'){const target=(match?.team_status||[]).find(x=>x.team_id===p.target_team_id);return`购买 ${target?.display_name||'目标企业'} 的规则许可情报`}
  if(action.action_type==='hold')return'本阶段不新增经营动作';
  return'参数已配置';
}
function renderPlan(){const root=$('#plan-list');if(!plan.length){root.innerHTML='<p class="muted">尚未添加决策；空方案会提交“保持经营”。</p>';return}root.innerHTML=plan.map((a,i)=>`<div class="plan-item"><strong>${i+1}. ${escapeHtml(actionNames[a.action_type]||'经营动作')}</strong><span>${escapeHtml(actionSummary(a))}</span><button data-remove="${i}" aria-label="删除此动作">×</button></div>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{plan.splice(+b.dataset.remove,1);renderPlan()})}
$('#clear-plan').onclick=()=>{plan=[];renderPlan()};
$$('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add;if(type==='loan'){const action_type=$('#loan-type').value,principal_wan=+$('#loan-amount').value,term=Math.max(1,+$('#loan-term').value||4);addAction({action_type,parameters:{principal_wan,...(action_type==='long_loan_borrow'?{term_years:term}:{term_quarters:term})}})}if(type==='factory')addAction({action_type:$('#factory-mode').value,parameters:{factory:$('#factory-name').value}});if(type==='line')addAction({action_type:'buy_product_line',parameters:{line_type:$('#line-type').value,product_id:$('#line-product').value}});if(type==='material')addAction({action_type:'material_order',parameters:{materials:{[$('#material-name').value]:+$('#material-quantity').value}}});if(type==='advertising')addAction({action_type:'advertising',parameters:{market:$('#ad-market').value,product_id:$('#ad-product').value,amount_wan:+$('#ad-amount').value}});if(type==='emergency-material')addAction({action_type:'emergency_purchase',parameters:{material_id:$('#emergency-material-name').value,quantity:+$('#emergency-material-quantity').value}});if(type==='emergency-product')addAction({action_type:'emergency_product_purchase',parameters:{product_id:$('#emergency-product-name').value,quantity:+$('#emergency-product-quantity').value}});if(type==='convert-line')addAction({action_type:'convert_product_line',parameters:{line_id:$('#asset-line').value,product_id:$('#convert-product').value}});if(type==='sell-line')addAction({action_type:'sell_product_line',parameters:{line_id:$('#asset-line').value}});if(type==='sell-factory')addAction({action_type:'sell_workshop',parameters:{factory_id:$('#asset-factory').value}});if(type==='spy')addAction({action_type:'spy_information_purchase',parameters:{target_team_id:$('#spy-team').value}})});
$('#submit-plan').onclick=async()=>{try{const action_bundle=plan.length?{actions:plan}:{action_type:'hold'},phase=match.decision_phase;const out=await api(`/api/matches/${match.match_id}/submit`,{method:'POST',body:JSON.stringify({action_bundle})});plan=[];match=out.match;render();message(out.submission.advanced?(phase==='operating'?'订单已经统一分配，请依据实际获单重新安排履约。':'本季度已结算，进入下一季度经营与申领。'):'决策已锁定，正在等待其他人类玩家。')}catch(err){message(err.message,'error')}};
$('#get-recommendation').onclick=async()=>{try{const profile=$('#agent-profile').value;message('协同 Agent 正在联合预演资金、资格、产能、履约和订单……');const out=await api(`/api/matches/${match.match_id}/recommend`,{method:'POST',body:JSON.stringify({profile})});plan=out.recommendation.actions||[out.recommendation];renderPlan();message(`已载入 ${plan.length} 个经过风险重放的建议动作。请检查后再提交，最终结果仍由模拟环境结算。`)}catch(err){message(err.message,'error')}};
function selectedOrderRows(){return $$('#orders-table input[data-order]:checked').map(box=>({box,order:JSON.parse(box.dataset.order)}))}
function claimAction(order,box,state){const ads=state.advertising||{},common={order_id:order.order_id,market:order.market,product:order.product,submitted_at:Math.random()};if(order.order_type==='竞单'){const bid=+(box?.closest('tr').querySelector('[data-bid]')?.value||order.total_price_wan);return {action_type:'auction_bid',parameters:{...common,bid_wan:bid}}}return {action_type:'select_order',parameters:{...common,product_advertising:+(ads[`${order.market}:${order.product}`]||0),market_advertising:Object.entries(ads).filter(([k])=>k.startsWith(`${order.market}:`)).reduce((s,[,v])=>s+(+v||0),0),total_advertising:Object.values(ads).reduce((s,v)=>s+(+v||0),0)}}}
$('#claim-selected').onclick=()=>{const state=match.observation?.private_state||{};selectedOrderRows().forEach(({box,order})=>addAction(claimAction(order,box,state)));$$('[data-screen="command"]')[0].click();message('选中的订单申领已加入本季度联合方案。')};
$('#claim-portfolio').onclick=()=>{const state=match.observation?.private_state||{},rows=selectedOrderRows(),selectedIds=new Set(rows.map(row=>String(row.order.order_id))),visible=match.observation?.public_state?.available_orders||[],candidateSlots=rows.map(({box,order})=>{const primaryQuantity=Number(order.quantity||0),primaryDue=Number(order.due_period_index??999),fallbacks=visible.filter(candidate=>{if(selectedIds.has(String(candidate.order_id))||String(candidate.product)!==String(order.product))return false;return Number(candidate.quantity||0)<=primaryQuantity&&Number(candidate.due_period_index??999)>=primaryDue}).slice(0,8);return [claimAction(order,box,state),...fallbacks.map(candidate=>claimAction(candidate,null,state))]});if(!candidateSlots.length){message('请先选择至少一个订单。','error');return}addAction({action_type:'order_portfolio',parameters:{candidate_slots:candidateSlots,target_count:candidateSlots.length}});$$('[data-screen="command"]')[0].click();message(`已加入 ${candidateSlots.length} 个组合申领槽位，每个槽位包含同产品回退候选。`)};
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v,d=0){return Number(v||0).toFixed(d)}
function dataRows(title,rows){return `<div class="data-section"><h4>${title}</h4>${rows.length?rows.map(([a,b])=>`<div class="data-row"><span>${escapeHtml(a)}</span><span>${escapeHtml(typeof b==='object'?JSON.stringify(b):b)}</span></div>`).join(''):'<p class="muted">暂无数据</p>'}</div>`}
function populateSelect(id,items){const el=$(id),old=el.value;el.innerHTML=items.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');if(items.includes(old))el.value=old}
function render(){if(!match)return;const post=match.decision_phase==='post_allocation',botOnly=match.human_slots===0,ownStatus=match.team_status.find(x=>x.team_id===match.player?.team_id);$('#match-id').textContent=match.match_id;$('#match-name').textContent=match.display_name||match.name;$('#match-mode').textContent=match.match_mode;$('#match-mode').className=`mode-badge mode-${match.match_mode==='人机对抗'?'hybrid':match.match_mode==='纯用户赛'?'human':'agent'}`;$('#match-meta').textContent=`${match.team_count} 家企业 · ${match.human_slots} 个人类席位 · ${match.team_count-match.human_slots} 个 Agent 席位 · XA 基准规则`;$('#period').textContent=match.period;$('#phase-pill').textContent=post?'获单后履约':'经营与申领';$('#status-pill').textContent={lobby:'等待加入',running:'比赛中',complete:'已结束'}[match.status]||match.status;$('#start-match').classList.toggle('hidden',match.status!=='lobby');$('#advance-bots').classList.toggle('hidden',!botOnly||match.status!=='running');$('#run-bots').classList.toggle('hidden',!botOnly||match.status!=='running');$('#export-match').classList.toggle('hidden',match.status!=='complete');$('#start-match').disabled=match.open_human_slots>0;$('#player-team').textContent=ownStatus?.display_name||(botOnly?'Agent 赛观战':'赛场观战');$$('.player-control').forEach(x=>x.classList.toggle('hidden',!match.player));$('#submit-plan').disabled=match.status!=='running'||match.submitted_this_period;$('#submit-plan').textContent=post?'提交获单后履约方案':'提交经营与申领方案';$('#submit-hint').textContent=botOnly?'使用顶部按钮推进一个决策阶段或直接运行至终局。':post?'提交后，环境独立执行生产、交付、违约、财务结算与破产判定。':'所有企业提交后，裁判按资格、广告、竞价和冲突规则统一分配订单。';$('#phase-explanation').textContent=post?'订单已经分配。请只根据本企业实际获单、库存和产能安排履约；你的预期不会替代环境的最终判定。':'获单前先统筹资金、资格、资产产能、采购与广告，再申领公开订单。此阶段尚不能假定一定获单。';
  $$('.stage-flow li').forEach(row=>row.classList.remove('active','complete'));const activeStage=post?'post_allocation':'operating';const order=['operating','allocation','post_allocation','settlement'],activeIndex=order.indexOf(activeStage);$$('.stage-flow li').forEach(row=>{const index=order.indexOf(row.dataset.stage);row.classList.toggle('active',index===activeIndex);row.classList.toggle('complete',index<activeIndex)});$('#ranking-title').textContent=`${match.match_mode}赛场状态`;
  if(match.status==='lobby'&&match.open_human_slots)message(`等待 ${match.open_human_slots} 位玩家加入。分享加入码：${match.match_id}`);else if(match.submitted_this_period)message('本季度决策已提交，等待其他玩家。');else if(match.status==='complete')message('比赛已经结束，可在赛场排名中查看终局结果。');else message('');
  const s=match.observation?.private_state||{},own=ownStatus||{};$('#metrics').innerHTML=[['现金',`${n(s.cash_wan)} 万`],['权益',`${n(s.owner_equity_wan)} 万`],['负债',`${n(s.debt_wan)} 万`],['评分代理',n(own.score,1)]].map(([a,b])=>`<div class="metric"><small>${a}</small><strong>${b}</strong></div>`).join('');$('#progress-text').textContent=`${Math.min(match.step,20)} / 20`;$('#progress-bar').style.width=`${Math.min(match.step/20*100,100)}%`;
  $('#capability-tags').innerHTML=[...(s.products||[]),...(s.markets||[]),...(s.iso||[])].map(x=>`<span>${escapeHtml(x)}</span>`).join('')||'<span>尚未开发</span>';const assigned=s.assigned_orders||[],delivered=s.delivered_orders||[],defaults=s.defaulted_orders||[];$('#order-summary').innerHTML=`在手订单：${assigned.filter(x=>!['已交','违约'].includes(x.status)).length}<br>累计交付：${delivered.length}<br>累计违约：${defaults.length}`;
  renderControls(s);renderOrders(match.observation?.public_state?.available_orders||[]);renderCompany(s);renderFeedback(s);renderRanking();renderPlan();
}
function renderControls(s){const c=match.rules_catalog||{};populateSelect('#factory-name',Object.keys(c.factories||{}));populateSelect('#line-type',Object.keys(c.production_lines||{}));populateSelect('#line-product',Object.keys(c.products||{}));populateSelect('#material-name',Object.keys(c.materials||{}));populateSelect('#ad-market',Object.keys(c.markets||{}));populateSelect('#ad-product',Object.keys(c.products||{}));populateSelect('#emergency-material-name',Object.keys(c.materials||{}));populateSelect('#emergency-product-name',Object.keys(c.products||{}));populateSelect('#convert-product',s.products||[]);populateSelect('#asset-line',(s.production_lines||[]).filter(x=>x.status==='ready').map(x=>x.line_id));populateSelect('#asset-factory',(s.factories||[]).filter(x=>x.ownership==='purchased').map(x=>x.factory_id));populateSelect('#spy-team',(match.team_status||[]).map(x=>x.team_id).filter(x=>x!==match.player?.team_id));const pending=new Set((s.pending_development||[]).map(x=>`${x.kind}:${x.target}`));const buttons=[];Object.keys(c.products||{}).filter(x=>!(s.products||[]).includes(x)&&!pending.has(`product:${x}`)).forEach(x=>buttons.push(`<button data-q="product" data-target="${x}">开发产品 ${x}</button>`));Object.keys(c.markets||{}).filter(x=>!(s.markets||[]).includes(x)&&!pending.has(`market:${x}`)).forEach(x=>buttons.push(`<button data-q="market" data-target="${x}">开发市场 ${x}</button>`));Object.keys(c.iso||{}).filter(x=>!(s.iso||[]).includes(x)&&!pending.has(`iso:${x}`)).forEach(x=>buttons.push(`<button data-q="iso" data-target="${x}">认证 ${x}</button>`));$('#qualification-actions').innerHTML=buttons.join('')||'<span class="muted">所有资格均已完成或在开发中</span>';$$('[data-q]').forEach(b=>b.onclick=()=>addAction({action_type:{product:'develop_product',market:'develop_market',iso:'develop_iso'}[b.dataset.q],parameters:{target:b.dataset.target}}));
  $('#receivable-actions').innerHTML=(s.receivables||[]).map(r=>`<button data-ar="${r.receivable_id}">贴现 ${r.receivable_id}（${n(r.amount_wan)}）</button>`).join('');$$('[data-ar]').forEach(b=>b.onclick=()=>addAction({action_type:'receivable_discount',parameters:{receivable_id:b.dataset.ar}}));
  const productionOptions=[];(s.production_lines||[]).filter(l=>l.status==='ready').forEach(l=>(l.line_type==='柔性线'?(s.products||[]):[l.product_id]).filter(Boolean).forEach(product=>productionOptions.push({line:l,product})));$('#production-actions').innerHTML=productionOptions.map((row,i)=>`<button data-prod="${i}">${escapeHtml(row.line.line_id)} · ${row.line.line_type}生产 ${row.product}</button>`).join('')||'<span class="muted">暂无就绪产线</span>';$$('[data-prod]').forEach(b=>{const row=productionOptions[+b.dataset.prod];b.onclick=()=>addAction({action_type:'production',parameters:{line_id:row.line.line_id,product_id:row.product,quantity:1,line_type:row.line.line_type}})});
  const outstanding=(s.assigned_orders||[]).filter(o=>!['已交','违约'].includes(o.status));$('#delivery-actions').innerHTML=outstanding.map(o=>`<button class="${(s.product_inventory?.[o.product]||0)>=o.quantity?'':'danger'}" data-deliver="${o.order_id}">交付 ${o.order_id} · ${o.product}×${o.quantity}</button>`).join('')||'<span class="muted">暂无待交订单</span>';$$('[data-deliver]').forEach(b=>b.onclick=()=>addAction({action_type:'order_delivery',parameters:{order_id:b.dataset.deliver}}));$$('[data-add],[data-q],[data-ar],[data-prod],[data-deliver]').forEach(b=>{let type={loan:$('#loan-type')?.value,factory:$('#factory-mode')?.value,line:'buy_product_line',material:'material_order',advertising:'advertising','emergency-material':'emergency_purchase','emergency-product':'emergency_product_purchase','convert-line':'convert_product_line','sell-line':'sell_product_line','sell-factory':'sell_workshop',spy:'spy_information_purchase'}[b.dataset.add];if(b.dataset.q)type={product:'develop_product',market:'develop_market',iso:'develop_iso'}[b.dataset.q];if('ar' in b.dataset)type='receivable_discount';if('prod' in b.dataset)type='production';if('deliver' in b.dataset)type='order_delivery';if(type)b.disabled=!allowed(type)});$('#claim-selected').disabled=!allowed('select_order')&&!allowed('auction_bid');$('#claim-portfolio').disabled=!allowed('order_portfolio');if(!match.information_purchase_enabled)$('[data-add="spy"]').disabled=true}
function renderOrders(orders){$('#orders-table').innerHTML=orders.slice(0,300).map(o=>`<tr><td><input type="checkbox" data-order='${escapeHtml(JSON.stringify(o))}'></td><td>${escapeHtml(o.order_id)}</td><td>${o.order_type}</td><td>${o.market}</td><td>${o.product}</td><td>${o.quantity}</td><td>${n(o.total_price_wan)}</td><td>${o.order_type==='竞单'?`<input class="bid-input" data-bid type="number" min="1" value="${n(o.total_price_wan)}">`:'-'}</td><td>${o.due_period}</td><td>${(o.required_iso||[]).join('+')||'-'}</td></tr>`).join('')||'<tr><td colspan="10" class="muted">本季度没有可见订单</td></tr>'}
function renderCompany(s){$('#assets-view').innerHTML=dataRows('资格',[['产品',(s.products||[]).join('、')],['市场',(s.markets||[]).join('、')],['ISO',(s.iso||[]).join('、')]])+dataRows('厂房',(s.factories||[]).map(x=>[x.factory_id,`${x.name} · ${x.ownership} · 容量 ${x.capacity}`]))+dataRows('生产线',[...(s.production_lines||[]),...(s.pending_lines||[])].map(x=>[x.line_id,`${x.line_type} · ${x.product_id} · ${x.status}`]))+dataRows('已购买情报',(s.intelligence_reports||[]).map(x=>[x.target_team_id,x.fields]));$('#finance-view').innerHTML=dataRows('产品库存',Object.entries(s.product_inventory||{}))+dataRows('原料库存',Object.entries(s.material_inventory||{}))+dataRows('长期贷款',(s.long_loans||[]).map(x=>[x.loan_id,`${n(x.principal_wan)} 万 · 到期 ${x.due_period_index}`]))+dataRows('短期贷款',(s.short_loans||[]).map(x=>[x.loan_id,`${n(x.principal_wan)} 万 · 到期 ${x.due_period_index}`]))+dataRows('应收款',(s.receivables||[]).map(x=>[x.receivable_id,`${n(x.amount_wan)} 万 · 到期 ${x.due_period_index}`]))}
function renderFeedback(s){const f=match.last_feedback,changes=f?.state_changes||{};$('#feedback-view').innerHTML=f?`<p class="${f.action_status==='accepted'?'status-ok':'status-bad'}">${f.action_status==='accepted'?'动作已接受':'动作存在拒绝'} · ${f.bankrupt?'已破产':'经营中'}</p><div class="change-grid"><span>现金 ${signed(changes.cash_wan)} 万</span><span>权益 ${signed(changes.owner_equity_wan)} 万</span><span>获单 +${changes.awarded_orders||0}</span><span>交付 +${changes.delivered_orders||0}</span><span>违约 +${changes.defaulted_orders||0}</span></div>${(f.action_rejections||[]).map(x=>`<div class="feedback-event status-bad">${escapeHtml(x)}</div>`).join('')}${(f.events||[]).slice(-12).map(x=>`<div class="feedback-event"><strong>${escapeHtml(x.event_type)}</strong> · ${escapeHtml(x.period||f.period)}</div>`).join('')}`:'<p class="muted">完成一次阶段提交后，这里会显示裁判实际接受的动作与状态变化。</p>';$('#review-view').innerHTML=f?`<div class="review-summary"><strong>${escapeHtml(f.period)} 复盘</strong><p>建议只依据实际结算改进下一次决策，不把 Agent 的预测当作裁判结果。</p></div>${(f.review_suggestions||[]).map((x,i)=>`<div class="review-item"><span>${i+1}</span><p>${escapeHtml(x)}</p></div>`).join('')}`:'<p class="muted">尚无可复盘的结算结果。</p>';$('#reports-view').innerHTML=(s.reports||[]).length?(s.reports||[]).map(r=>dataRows(`第 ${r.year} 年`,[['净利润',r.income_statement?.net_income_wan],['总资产',r.balance_sheet?.total_assets_wan],['权益',r.balance_sheet?.owner_equity_wan],['净现金流',r.cash_flow_statement?.net_cash_flow_wan]])).join(''):'<p class="muted">年度结束后自动生成资产负债表、利润表和现金流量表。</p>'}
function signed(value){const number=Number(value||0);return`${number>=0?'+':''}${number.toFixed(1)}`}
function renderRanking(){const rows=[...(match.team_status||[])].sort((a,b)=>(b.score||0)-(a.score||0));$('#ranking-table').innerHTML=rows.map((r,i)=>`<tr><td><strong>${i+1}. ${escapeHtml(r.display_name||r.team_id)}</strong><small class="participant-tag ${r.participant_type}">${r.participant_type==='human'?'人类':'Agent'}</small></td><td>${escapeHtml(r.strategy_label||'-')}</td><td class="${r.bankrupt?'status-bad':'status-ok'}">${r.bankrupt?'破产':'经营中'}</td><td>${n(r.development_potential,0)}</td><td>${n(r.score,1)}</td></tr>`).join('')}
if(auth?.matchId)refresh();else showLobby();setInterval(()=>{if(auth?.matchId&&match?.status!=='complete')refresh()},2500);
